service: aws-aho-tarea1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  getItems:
    handler: ./src/list.getItems
    events: # Que eventos se pueden realizar
      - httpApi: # Eventos tipos http
          path: /items/ # Path de acceso al evento
          method: get # Metodo que acepta el evento http
  createItem:
    handler: ./src/create.createItem
    events:
      - httpApi:
          path: /item/
          method: post
